const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], KEY='aquasense_history_v1';
const R={ph:['pH',6.5,8.5,7.4,''],turbidity:['Turbidity',null,5,1.5,' NTU'],tds:['TDS',null,500,250,' mg/L'],do:['Dissolved Oxygen',5,null,8,' mg/L'],nitrate:['Nitrate',null,45,10,' mg/L'],temperature:['Temperature',10,30,24,' °C'],conductivity:['Conductivity',null,800,350,' µS/cm']};
function hist(){return JSON.parse(localStorage.getItem(KEY)||'[]')} function save(h){localStorage.setItem(KEY,JSON.stringify(h.slice(0,50)))} function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function score(v,k){let [label,min,max,ideal,unit]=R[k],p=0,bad=false,reason='';if(min&&v<min){p=Math.min(45,(min-v)*10);bad=true;reason='Below '+min+unit}else if(max&&v>max){p=Math.min(45,(v-max)/max*100);bad=true;reason='Above '+max+unit}else{p=Math.min(8,Math.abs(v-ideal)/(ideal||1)*6)}if(k==='ph'&&v>=min&&v<=max)p=Math.abs(v-ideal)*2;if(k==='do'&&v<5){p=40;bad=true;reason='Low dissolved oxygen'}return{p,bad,reason}}
function analyze(v){let total=0,pen=0,b=[];Object.keys(R).forEach(k=>{let x=score(+v[k],k),w=({ph:1.4,turbidity:1.5,tds:1,do:1.4,nitrate:1.2,temperature:.7,conductivity:.8})[k];total+=w;pen+=x.p*w;if(x.bad)b.push({k,label:R[k][0],value:v[k],unit:R[k][4],reason:x.reason})});let s=Math.round(Math.max(0,Math.min(100,100-pen/total*1.9)));if(b.length>=3)s=Math.max(0,s-8);let q=s>=90?'Excellent':s>=75?'Good':s>=55?'Moderate':s>=35?'Poor':'Critical',risk=s>=80?'Low':s>=60?'Medium':s>=35?'High':'Critical',rec=[];if(!b.length)rec.push('All entered parameters are within the simplified reference ranges.');b.forEach(x=>rec.push(`Review ${x.label}: ${x.reason}. Consider confirmatory testing.`));if(+v.turbidity>5)rec.push('Investigate possible suspended solids, runoff, or filtration issues.');if(+v.nitrate>45)rec.push('Investigate nutrient sources and possible agricultural or wastewater influence.');if(+v.do<5)rec.push('Low dissolved oxygen can indicate organic loading or poor aeration; investigate the source.');if(s<75)rec.push('Do not rely on this dashboard alone for drinking-water safety; use certified laboratory testing.');return{score:s,quality:q,risk,disturbances:b,recommendations:rec}}
function ring(el,s){el.style.background=`conic-gradient(var(--cyan) ${s*3.6}deg,#ffffff12 ${s*3.6}deg)`}
function fill(v,r){$('#rscore').textContent=r.score;ring($('#rring'),r.score);$('#rquality').textContent=r.quality+' Water Quality';$('#rsummary').textContent=`${r.disturbances.length} parameter disturbance${r.disturbances.length===1?'':'s'} detected.`;$('#rrisk').textContent=r.risk;$('#rreason').textContent=r.risk==='Low'?'No major risk indicators were detected.':`${r.disturbances.length} parameter(s) require attention.`;$('#rbadge').textContent=r.quality.toUpperCase();$('#rtitle').textContent=v.sample||'Water Sample';$('#disturbances').innerHTML=r.disturbances.length?r.disturbances.map(x=>`<div class="disturbance"><b>${x.label}</b> — ${x.value}${x.unit} · ${x.reason}</div>`).join(''):'No disturbances detected.';$('#recs').innerHTML=r.recommendations.map(x=>`<li>${x}</li>`).join('')}
function dash(v,r){$('#dscore').textContent=r.score;$('#dquality').textContent=r.quality+' water';$('#drisk').textContent=r.risk;$('#drisktext').textContent=r.disturbances.length+' disturbance(s)';$('#dcount').textContent=hist().length;$('#oscore').textContent=r.score;ring($('#oring'),r.score);$('#meter').style.width=r.score+'%';$('#otitle').textContent=r.quality+' water quality';$('#odesc').textContent=r.disturbances.length?`${r.disturbances.length} parameter(s) need attention.`:'No major parameter disturbances detected.';$('#obadge').textContent=r.quality.toUpperCase();$('#latest').innerHTML=Object.keys(R).map(k=>{let x=score(+v[k],k);return `<div class="param"><b>${R[k][0]} <small>${x.bad?'Attention':'OK'}</small></b>${v[k]}${R[k][4]}</div>`}).join('')}
function render(){let h=hist();$('#dcount').textContent=h.length;$('#tbody').innerHTML=h.length?h.map(x=>`<tr><td>${new Date(x.date).toLocaleString()}</td><td>${x.v.sample||'Unnamed'}</td><td><b>${x.r.score}</b></td><td>${x.r.quality}</td><td>${x.r.risk}</td><td>${x.r.disturbances.length}</td></tr>`).join(''):'<tr><td colspan="6">No analyses saved yet.</td></tr>'}
function go(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));$('#title').textContent={dashboard:'Water Quality Dashboard',analyzer:'Analyze Water',history:'Analysis History',about:'About AquaSense AI'}[id];$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#new').onclick=$('#hero').onclick=()=>go('analyzer');$('#demo').onclick=()=>Object.entries({ph:7.2,turbidity:2.1,tds:280,do:7.1,nitrate:12,temperature:24,conductivity:420,sample:'River Sample A'}).forEach(([k,v])=>$('#form').elements[k].value=v);
$('#form').onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target)),r=analyze(v),h=hist();h.unshift({date:new Date().toISOString(),v,r});save(h);fill(v,r);dash(v,r);render();toast('Analysis completed and saved locally.')};
$('#clear').onclick=()=>{if(confirm('Delete all saved analyses?')){localStorage.removeItem(KEY);render();toast('History cleared.')}};$('#export').onclick=()=>{let h=hist();if(!h.length)return toast('No history to export.');let rows=[['Date','Sample','Score','Quality','Risk','Disturbances'],...h.map(x=>[x.date,x.v.sample||'',x.r.score,x.r.quality,x.r.risk,x.r.disturbances.map(d=>d.label).join('; ')])];let csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='aquasense-history.csv';a.click()};$('#theme').onclick=()=>{let l=document.documentElement.dataset.theme==='light';document.documentElement.dataset.theme=l?'':'light';localStorage.setItem('theme',l?'dark':'light')};if(localStorage.getItem('theme')==='light')document.documentElement.dataset.theme='light';let h=hist();if(h[0]){fill(h[0].v,h[0].r);dash(h[0].v,h[0].r)}render();
